<?php

declare(strict_types=1);

namespace App\Components\Device\Show\Measurement\Grid\Item;

use App\Components\Device\Show\Measurement\Grid\Control;
use App\Model\ConsumptionManager;
use App\Model\Entity\ConsumptionResource;
use http\Encoding\Stream\Inflate;
use Nette\Application\UI\Multiplier;
use Nette\Database\Table\ActiveRow;
use Nette\Database\Table\Selection;
use Closure;

trait ControlMultipleTrait
{
    private Selection $consumptions; // Selection is accessible via array access
    private ControlFactory $deviceShowMeasurementGridItemControlFactory;
    private ConsumptionManager $consumptionManager;

    public function injectDeviceShowMeasurementGridItem(\App\Components\Device\Show\Measurement\Grid\Item\ControlFactory $controlFactory)
    {
        $this->deviceShowMeasurementGridItemControlFactory = $controlFactory;
    }

    public function createComponentConsumtionsGridItemMultiple()
    {
        $manager = $this->consumptionManager; // return Selection with individual measurements for the device
        $factory = $this->deviceShowMeasurementGridItemControlFactory; //returns the factory to create one item of item
        $onDeleteCallback = Closure::fromCallable([$this, 'onMeasurementDelete']);

        // the anonymous function is generated by the Closure class

        return new Multiplier(function (string $id) use ($manager, $factory, $onDeleteCallback){

            bdump($manager->getMeasurementById((int) $id));

            return $factory->create(
              $manager->wrapToEntity($manager->getMeasurementById((int) $id)),
              $onDeleteCallback,
            );

        });

    }

    public function onMeasurementDelete(): void
    {
        $this->redrawControl('consumption');
    }
}