<?php

namespace App\AdminModule\Presenters;

trait SecurePresenterTrait
{
    protected function startup()
    {
        if (!$this->isLinkCurrent('Sign:in') && !$this->user->isAllowed('admin', 'view')) {
            $this->flashMessage('Pre prístup do tejte sekcie, je potrebné oprávnenie používateľa.', 'error');
            $this->redirect('Sign:in');
        }
        parent::startup(); // TODO: Change the autogenerated stub
    }
}