CREATE TABLE `device` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '0' COLLATE 'utf8_slovak_ci',
  `room` VARCHAR(255) NOT NULL DEFAULT '0' COLLATE 'utf8_slovak_ci',
  `image` VARCHAR(255) NOT NULL DEFAULT '0' COLLATE 'utf8_slovak_ci',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
)
    COLLATE='utf8_slovak_ci'
    ENGINE=InnoDB
    AUTO_INCREMENT=6;
