CREATE TABLE `post`
(
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL DEFAULT '0' COLLATE 'utf8_slovak_ci',
    `content` TEXT NOT NULL COLLATE 'utf8_slovak_ci',
    `status` INT(1) NOT NULL DEFAULT '0',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_slovak_ci'ENGINE=InnoDB AUTO_INCREMENT=22;
